### ISSUE TITLE
WARNING out-of-order frame: 9266

### ISSUE THREAD

**Issue by vladfi1** [hohav/py-slippi#11]
A lot of Gang-Steals files are starting to give me warnings like

WARNING out-of-order frame: 9266

And then I see a frame with index 9266 which is indeed out of order, and which has empty ports data `(None, None, None, None)`.

An example file is `Gang-Steals/6/Game_20190309T152547.slp`.

**Comment by hohav** [comment]
Thanks for the report. I downloaded what I *think* is the same [replay](https://storage.googleapis.com/slippi.appspot.com/replays/3-6-Game_20190309T152547.slp) you're using from slippi.gg, but I'm not seeing any warnings.

What version of py-slippi are you using? Where did you download this replay from, and what's its MD5 checksum?

**Comment by hohav** [comment]
I believe this was resolved on discord (please re-open if not).
