### ISSUE TITLE
Player name value?

### ISSUE THREAD

**Issue by noahpodgurski** [hohav/py-slippi#14]
I have been looking at the API's written, and cannot seem to find any record of the player name, i.e., the netplay/smashladder name linked with the game. In case I am not explaining this well, allow me to elaborate.

When I open my smashladder application, it brings up my list of past games on the right. When I click the 'i' info button, it shows my stats and then it shows my name above the character I was playing as.

My question is, how do I access my name from the API? How does it know which character I was playing as? Has it not been added in yet? I am still very new to this so any help would be very appreciated, thanks!

**Comment by hohav** [comment]
As far as I know, that information is not available to Slippi and therefore isn't included in the replays it generates. The player's in-game tag is available, but that's only useful if you consistently use one.

For a better explanation, try asking the [Slippi discord](https://discord.gg/XpHZex6).

**Comment by NikhilNarayana** [comment]
> As far as I know, that information is not available to Slippi and therefore isn't included in the replays it generates. The player's in-game tag is available, but that's only useful if you consistently use one.
> 
> For a better explanation, try asking the [Slippi discord](https://discord.gg/XpHZex6).

It is recorded in the metadata, but only for dolphin games.

**Comment by hohav** [comment]
Netplay names are [implemented](https://github.com/hohav/py-slippi/commit/ac305e476be3bbdf7b40e063a6f9cecae8e615fd) in py-slippi 1.4.1, just released. Thanks to @NikhilNarayana for the PR.
