### ISSUE TITLE
Support construction of Game objects from PathLike objects in addition to str and streams.

### ISSUE THREAD

**Issue by Kered13** [hohav/py-slippi#25]
The ability to construct a Game object from a PathLike object was broken when [event driven parsing](https://github.com/hohav/py-slippi/commit/f110af7ed43cc6b68ed798c691fbd5d406044499#diff-09ad0b0331e8b0b8258da7d5f6d53cf094d1c0ad2c21ab869ccf3f80d531ef71) was introduced.

The new parsing logic checks if the input is a `str` in the `parse()` function, and if so treats it as a path and opens it. Otherwise, the input is treated as a stream. This breaks the ability to support any representation of a path other than a `str`. This is a problem because paths are frequently manipulated using the built-in PathLib library.

A simple solution would be to add a check for `isinstance(input, os.PathLike)` in addition to `str` in the `parse()` function. A more sophisticated solution might try to check the attributes of `input` to determine if it is path-like or stream-like.

**Comment by hohav** [comment]
Thanks for the report. Should be fixed by c642857, but please re-open if the fix doesn't work for you.
