### ISSUE TITLE
ValueError: time data '2019-03-09T16:20:03' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

### ISSUE THREAD

**Issue by footykid3** [hohav/py-slippi#3]
Mac Os Mojave
Slippi Build  1.3.2

Having problems with trying to parse information from the files  from the gang tournament

**Used the following command to download the py-slippi build from github:**
pip install git+https://github.com/hohav/py-slippi

**Getting the error:** ValueError: time data '2019-03-09T08:54:03' does not match format '%Y-%m-%dT%H:%M:%S.%f%z'

And it seems to be any file from the gang tournament

**Comment by hohav** [comment]
Those dates were missing time zones, causing py-slippi's date parsing to fail. I made that more lenient, which fixed things in my tests. Can you fetch the latest master and try again?

**Comment by sverona** [comment]
This is fixed in master but still needs to be pushed to pip.

**Comment by hohav** [comment]
[Fixed](https://github.com/hohav/py-slippi/commit/f2a5aea12c6bfad7af7d6df397c7d3792fb9c23c), and included in [release 1.2.0](https://github.com/hohav/py-slippi/releases/tag/v1.2.0).
